# 机器人基本信息配置
bot:
  # 机器人QQ号
  qq: 2540936290
  # Mirai-api-http 地址
  host: 10.0.0.200
  # Mirai-api-http 端口
  port: 26668
  # Mirai-api-http authKey
  key: 1145141919810

# 数据库配置
mysql:
  # 数据库地址
  host: 127.0.0.1
  # 数据库端口
  port: 3306
  # 数据库用户名
  user: root
  # 数据库密码
  password: root
  # 数据库名
  database: nia

# 插件配置
plugins:
 - survival_test
 - message_forward
 - mcsmanager
 - operational_irregularities

# 插件详细配置

# survival_test机器人存活状态测试
# 向机器人发送指定命令，检测是否存活
survival_test:
  # 命令发送人QQ 可以是自己
  commandSender: 
  - 1287756886
  # 触发词
  command: /ping
  # 响应词
  response: pang!

# message_forward机器人消息转发
# 将机器人接收到的私聊信息转发给指定人（一定不要写机器人自己！！！！！）
message_forward:
  # 接收消息的人（系统不会转发接收人列表中的消息）
  addressee: 
  - 1287756886

# 将 Mcsmanager 面板对接 QQ 群
# 让 QQ 群中的成员可以管理 Mcsmanager 中的实例
mcsmanager:
  # 实例列表
  examples:
    - name: test1
      gid: b7628ebd17b845f4acd385a9e8cfaede
      uid: 90d1f6d3dd5b47db8b1d221eccd0a86c
      mcsm_url: http://10.0.0.200:23333
      mcsm_key: 233333
      qq_group: 
        - 856942056

# 娱乐向插件 operational_irregularities
# 用于检测群友业务违规然后反馈 这个模块写死了，需要直接修改源码
operational_irregularities:
  # 监听 QQ 群
  group: 
    - 856942056
  # 接收通知的人
  addressee:
    - 1287756886